config/routes.rb
Rails.application.routes.draw do

  root "pages#index"

  devise_for :users,
             :skip         => [:sessions],
             :controllers  => { :omniauth_callbacks => "users/omniauth_callbacks" }

  as :user do
    match "login",   :to => "sessions#new",      :via => :get,     :as => :new_user_session
    match "logout",  :to => "sessions#destroy",  :via => :delete,  :as => :destroy_user_session
  end

  resources :users, :only => [:show, :edit, :update] 
  resources :recipes

  get :paginate, :as => :paginate, :to => "pages#paginate"
  get :search,   :as => :search,   :to => "pages#search"

  resources :votes, :only => [] do
    post :toggle,   :on => :member, :as => :toggle
    post :create,   :on => :member, :as => :create
    post :destroy,  :on => :member, :as => :destroy
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  belongs_to :user
  has_many   :votes

  validates :title,    :presence => true, :length  => { :maximum => 255 }
  validates :tagline,  :presence => true, :length  => { :maximum => 255 }
  validates :link,     :presence => true
  validates :user,     :presence => true

  validate  :user_under_limit?

  validates_format_of :link, :with => /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i,   :message => "Please use a valid url"
  validates_format_of :image, :with => /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i,  :message => "Please use a valid url", :allow_nil => true

  def self.ordered
    order("votes_count DESC")
  end

  def self.filter_by_date(start_date, end_date)
    where(:created_at => start_date.to_time..end_date.to_time)
  end

  def user_under_limit?
    if Recipe.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day, user: user).count > 1
      errors.add(:user, "You can't post more than two times a day")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :recipes
  has_many :votes

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name      = auth.info.name
      user.email     = auth.info.email
      user.image     = auth.info.image + "?type=large"
      user.password  = Devise.friendly_token[0,20]
    end
  end

  def submitted
    Recipe.where(:user => self)
  end

  def voted
    recipes = []

    votes = Vote.where(:user => self)
    votes.each do |vote|
      recipes.push(vote.recipe)
    end
    recipes
  end

  def voted?(recipe)
    recipe.votes.each do |vote|
      if vote.user = self
        return true
      end
    end

    false
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe, :counter_cache => true

  validates :user, :presence => true
  validates :recipe, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def new_session_path(scope)
    new_user_session_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @date = Time.now.to_date
    @recipes = Recipe.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end

  def paginate
    @date = Date.parse(params["date"])

    if @date == Date.today
      @recipes = Recipe.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
    else
      @recipes = Recipe.where(created_at: @date.beginning_of_day..@date.end_of_day)
    end
    
    respond_to do |format|
      format.js { render layout: false, content_type: 'text/javascript' }
    end
  end

  def search
    @query = params[:q]

    if @query.empty?
      @recipes = Recipe.ordered
    else
      @recipes = Recipe.fuzzy_search(@query)
    end

    respond_to do |format|
      format.js { render layout: false, content_type: 'text/javascript'}
      format.json {}
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

    def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :tagline, :link, :image, :user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def new
    super
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, :except => [:show]

  def show
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:recipe).permit(:job, :username)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user!

  def toggle
    @recipe = Recipe.find(params[:id])

    if params[:voted] == "true"
      @vote = @recipe.votes.find_by(:user => current_user)
      @vote.destroy

      render :json => { :recipe => @recipe.id, :type => "destroy" }
    else
      create(@recipe.id)
    end
  end

  private

  def create(recipe_id)
    @recipe = Recipe.find(recipe_id)
    @vote = @recipe.votes.new(:user => current_user)

    if @vote.save
      render :json => { :recipe => @recipe.id, :type => "create" }
    else
      render :json => { :success => false }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Food
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "shared/navbar"
    .notices{:style => "margin: 10px;"}
      %p.notice.alert-dismissible.alert-warning= notice
    #content.container
      = yield

app/views/pages/_recipes.haml
.page-header
  .row
    %h1#header
      - if @date == Time.now.to_date
        Today
      - elsif @date == Date.yesterday
        Yesterday
      - else
        = @date.strftime("%B #{@date.day.ordinalize}")
      - if @date < Time.now.to_date
        = link_to 'Next Day', paginate_path(:date => @date.to_date.next_day, :dir => :future), :remote => true, :class => "btn btn-default pull-right paginators", :style => "margin-left: 10px"
      = link_to 'Previous Day', paginate_path(:date => @date.to_date.prev_day, :dir => :past), :remote => true, :class => "btn btn-default pull-right paginators"
.row
  = render @recipes

app/views/pages/_search.haml
#content
  .page-header
    .row
      %h1#header
        = "Search results for \"#{@query}\""
        = link_to 'Back', "", :class => "btn btn-default pull-right paginators"

  .row
    = render @recipes

app/views/pages/index.haml
= render "recipes"

app/views/pages/paginate.js.erb
$("#content").fadeOut("slow", function() {
  $("#content").html("<%= j render(:partial => 'recipes') %>")
})
$("#content").fadeIn("slow")

app/views/pages/search.js.erb
$("#header").text("Search results for \"#{@query}\"")
$("#content").html("<%= j render(:partial => 'search') %>")

app/views/recipes/_form.haml
- if @recipe.errors.messages[:user]
  %p.notice.alert-dismissible.alert-warning{:style => "padding: 10px"}
    = @recipe.errors.messages[:user].first

= form_for @recipe, :html => { :class => "form-horizontal" } do |f|
  %fieldset
    .form-group
      = f.label :title, :class => "control-label col-md-2"
      .col-md-10
        = f.text_field :title, :class => "form-control"
        = f.error_message_on :title, :class => "form-control"
    .form-group
      = f.label :tagline, :class => "control-label col-md-2"
      .col-md-10
        = f.text_field :tagline, :class => "form-control"
        = f.error_message_on :tagline, :class => "form-control"
    .form-group
      = f.label :link, :class => "control-label col-md-2"
      .col-md-10
        = f.text_field :link, :class => "form-control"
        = f.error_message_on :link, :class => "form-control"
    .form-group
      = f.label :image, :class => "control-label col-md-2"
      .col-md-10
        = f.text_field :image, :class => "form-control"
        = f.error_message_on :image, :class => "form-control"
    .form-group
      = f.submit "Submit", :class => "col-md-10 col-md-offset-2 btn btn-primary"

app/views/recipes/_recipe.haml
.col-md-12
  .panel.panel-default
    .panel-heading
      %strong
        = recipe.title
      %p.pull-right
        %strong
          .votes.pull-right{:id => "#{recipe.id}"}
            = recipe.votes.count
          .pull-right{:style => "margin-right: 5px"}
            Votes:

    .panel-body
      = recipe.tagline
      %div.swag.pull-right{:style => "margin-left: 10px;"}
        - if current_user
          - if current_user.voted?(recipe)
            = link_to "Unvote", toggle_vote_path(:id => recipe.id, :voted => true ), :remote => true, :method => :post, :id => "vote-#{recipe.id}", :class => "btn btn-success col-md-12 vote"
          - else
            = link_to "Vote", toggle_vote_path(:id => recipe.id, :voted => false ), :remote => true, :method => :post, :id => "vote-#{recipe.id}", :class => "btn btn-primary col-md-12 vote"
        - else
          = link_to "Vote", new_user_session_path, :class => "btn btn-primary col-md-12 "
      = link_to "Try it out", recipe.link, :class => "btn btn-info pull-right"

app/views/recipes/edit.haml
%h1 Edit your recipe
= render "form"

app/views/recipes/new.haml
.container
  .row
    .page-header
      %h1 Post a new recipe
  .row
    = render "form"

app/views/recipes/show.haml
%p
  %strong Title:
  = @recipe.title
%p
  %strong Tagline:
  = @recipe.tagline
%p
  %strong Submitter:
  = @recipe.user.email


= link_to 'Edit', edit_recipe_path(@recipe) if current_user == @recipe.user
= link_to 'Back', recipes_path

app/views/shared/_navbar.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %strong
        = link_to "Foodhunt", root_path,  :class => "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      .nav.navbar-nav.navbar-left
        = text_field_tag :search, nil, :placeholder => "Search for a recipe...", :class => "form-control pull-left", :style => "margin: 7px; ", :size => "100", :id => "search"
      %ul.nav.navbar-nav.navbar-right
        %li
          .form-group
            = link_to "+ Post a new recipe", new_recipe_path, :class => "btn btn-warning form-control", :style => "margin-top:10px; "
        - if current_user
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = image_tag current_user.image, :width => 24, :height => 24, :style => "border-radius: 50%"
              %i.fa.fa-caret-down
            %ul.dropdown-menu
              %li
                = link_to "Profile", user_path(current_user)
              %li
                = link_to "Logout", destroy_user_session_path, :method => :delete
        - else
          %li
            = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)

app/views/users/show.haml
.row
  .col-md-6.col-md-offset-5
    = image_tag @user.image, :width => 150, :height => 150, :style => "border-radius: 50%;"

.name{:style => "padding-top:20px"}
  = @user.name

.job
  - if @user.job?
    = @user.job
  - elsif @user == current_user
    .form-group.col-md-4.col-md-offset-4
      .input-group{:style => "padding-top:20px"}
        = text_field_tag :job,"", :placeholder => "Add a job title...", :class => "form-control", :id => "add_job"
        = link_to "Submit", "javascript:void(0)", :class => "input-group-addon"
  - else

.row
  .col-md-12
    %h1.bleh Submitted
  = render @user.submitted
.row
  .col-md-12
    %h1.bleh Voted
  = render @user.voted

app/views/votes/create.js.erb
console.log("hello")